micronaut:
  application:
    name: demo
  server:
    port: -1
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    schema-generate: CREATE_DROP
    dialect: MYSQL
test-resources:
  containers:
    mysql:
      image-name: mysql:8.2
