= Micronaut Gradle plugin
:native-build-tools-version: 0.9.13
:kotlin-version: 1.6.21
:micronaut-version: 3.5.1
:gradle-version: 7.5.1
:shadow-version: 7.1.2
:native-gradle-plugin: https://graalvm.github.io/native-build-tools/{native-build-tools-version}/gradle-plugin.html
:gradle-docs: https://docs.gradle.org/{gradle-version}/userguide
:gradle-toolchains: {gradle-docs}/toolchains.html
:default-docker-image: openjdk:17-alpine
:docker-plugin: https://github.com/bmuschko/gradle-docker-plugin
:aws-docs: https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#customRuntimes
:testresources-guide: https://micronaut-projects.github.io/micronaut-test-resources/latest/guide

Version {gradle-project-version}

== What's new

NOTE: Documentation for the 2.x branch can be found https://github.com/micronaut-projects/micronaut-gradle-plugin/tree/2.0.x#readme[here].

The 3.0.0 version of the plugin integrates with the {native-gradle-plugin}[official GraalVM plugin] which introduces some breaking changes:

    - the `nativeImage` task is now replaced with `nativeCompile`
    - native image configuration happens in the `graalvmNative` DSL block
    - The GraalVM SDK being used depends on how you configure {gradle-toolchains}[toolchains]

Please refer to the <<native-image, native image section>> for more help: the <<toolchain-behavior,toolchain selection mechanism might be surprising to you>>.

== The Gradle plugins

A Gradle Plugin which makes development of Micronaut application and libraries a breeze.

This project currently consists of different plugins:

- the https://plugins.gradle.org/plugin/io.micronaut.application[`io.micronaut.application`] plugin is aimed at building Micronaut applications. It automatically integrates with GraalVM by applying the `io.micronaut.graalvm` plugin transparently.
- the https://plugins.gradle.org/plugin/io.micronaut.library[`io.micronaut.library`] plugin is aimed at building Micronaut libraries.
- the https://plugins.gradle.org/plugin/io.micronaut.graalvm[`io.micronaut.graalvm`] plugin integrates with the official {native-gradle-plugin}[GraalVM Native Build Tools plugin] and configures it for Micronaut applications.
- the https://plugins.gradle.org/plugin/io.micronaut.aot[`io.micronaut.aot`] plugin integrates with Micronaut AOT to produce optimized binaries.

=== Individual plugins

In addition to the library and application plugins described in the following documentation, you can apply one of the following plugins to your project.
For example, the `minimal` plugins can be used to reduce the number of tasks, for example if you don't need Docker or GraalVM support:

[cols=3,options=header]
|===
|Plugin id
|Description
|Also applies

|https://plugins.gradle.org/plugin/io.micronaut.minimal.library[`io.micronaut.minimal.library`]
|Allows building Micronaut libraries, without GraalVM support
|`java-library`

|https://plugins.gradle.org/plugin/io.micronaut.minimal.application[`io.micronaut.minimal.application`]
|Allows building Micronaut applications, without GraalVM nor Docker support
|`application`

|https://plugins.gradle.org/plugin/io.micronaut.graalvm[`io.micronaut.graalvm`]
|Adds support for building native images
|

|https://plugins.gradle.org/plugin/io.micronaut.docker[`io.micronaut.docker`]
|Adds support for building Docker images
|

|https://plugins.gradle.org/plugin/io.micronaut.aot[`io.micronaut.aot`]
|Adds support for Micronaut AOT
|

|https://plugins.gradle.org/plugin/io.micronaut.library[`io.micronaut.library`]
|A typical Micronaut Library, with support for GraalVM
|https://plugins.gradle.org/plugin/io.micronaut.minimal.library[`io.micronaut.minimal.library`], https://plugins.gradle.org/plugin/io.micronaut.graalvm[`io.micronaut.graalvm`], `AptEclipsePlugin`

|https://plugins.gradle.org/plugin/io.micronaut.application[`io.micronaut.application`]
|A typical Micronaut Application, with support for GraalVM and Docker
|https://plugins.gradle.org/plugin/io.micronaut.minimal.application[`io.micronaut.minimal.application`], https://plugins.gradle.org/plugin/io.micronaut.graalvm[`io.micronaut.graalvm`], https://plugins.gradle.org/plugin/io.micronaut.docker[`io.micronaut.docker`], `AptEclipsePlugin`

|https://plugins.gradle.org/plugin/io.micronaut.test-resources[`io.micronaut.test-resources`]
|Provides automatic test resources provisioning on a single project
|

|https://plugins.gradle.org/plugin/io.micronaut.test-resources-consumer[`io.micronaut.test-resources-consumer`]
|Provides ability to use test resources of other projects of multiproject builds
|

|===

Using the `io.micronaut.application` plugin:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id 'io.micronaut.application' version '{gradle-project-version}'
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id("io.micronaut.application") version "{gradle-project-version}"
}
----

is therefore equivalent to applying those plugins individually:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id 'io.micronaut.minimal.application' version '{gradle-project-version}'
  id 'io.micronaut.docker' version '{gradle-project-version}'
  id 'io.micronaut.graalvm' version '{gradle-project-version}'
}
apply plugin: com.diffplug.gradle.eclipse.apt.AptEclipsePlugin
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id("io.micronaut.application") version "{gradle-project-version}"
  id("io.micronaut.docker") version "{gradle-project-version}"
  id("io.micronaut.graalvm") version "{gradle-project-version}"
}
apply(plugin=com.diffplug.gradle.eclipse.apt.AptEclipsePlugin::class.java)
----

`io.micronaut.minimal.application`, `io.micronaut.graalvm` and `io.micronaut.docker` plugins (as well as the Eclipse annotation processing support plugin).

== Quick Start

Template projects are available via https://micronaut.io/launch/[Micronaut Launch] for each language.

To get started you can use the Micronaut CLI:

[source, bash]
----
$ mn create-app demo --lang java
$ mn create-app demo --lang groovy
$ mn create-app demo --lang kotlin
----

Or if you don't have it installed via `curl`:

[source, bash]
----
# for Java
$ curl https://launch.micronaut.io/demo.zip?lang=java \
  -o demo.zip && unzip demo.zip -d demo && cd demo
# for Groovy
$ curl https://launch.micronaut.io/demo.zip?lang=groovy \
  -o demo.zip && unzip demo.zip -d demo && cd demo
# for Kotlin
$ curl https://launch.micronaut.io/demo.zip?lang=kotlin \
  -o demo.zip && unzip demo.zip -d demo && cd demo
----

== Micronaut Library Plugin

.Applying the plugin
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id 'io.micronaut.library' version '{gradle-project-version}'
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id("io.micronaut.library") version "{gradle-project-version}"
}
----

The https://plugins.gradle.org/plugin/io.micronaut.library[Micronaut library plugin] applies the following modifications to the build:

* Applies the https://search.maven.org/artifact/io.micronaut/micronaut-bom[Micronaut Bill of Materials (BOM)]
* Applies the `java-library` plugin
* Configures annotation processing for the current language (Groovy, Java or Kotlin)

The `micronaut` DSL can be used to configure how this behaves.

The minimum requirement is to set the Micronaut version to use. This can be done by setting `micronautVersion` in `gradle.properties` or as follows in `build.gradle(.kts)`:

.Selecting the Micronaut version
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    version "{micronaut-version}"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    version.set("{micronaut-version}")
}
----

Complete example with the default settings:

.Micronaut configuration options
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    version "{micronaut-version}"
    processing {
        // Sets whether incremental annotation processing is enabled
        incremental true
        // Sets the module name.
        // This should be the same as the artifactId in the POM
        module project.name
        // Sets the group.
        // This should be th same as the groupId in the POM
        group project.group
        // Sets the Java package names containing any custom Micronaut
        // meta annotations (new annotations annotated with say @Around).
        // Generally used only for advanced cases such as defining new AOP
        // advice. If omitted however, incremental annotation processing
        // will not work correctly
        annotations "com.example.*"
        // additional sourceSets can be configured here to apply the BOM
        // and annotation processors to source sets other than 'main'
        sourceSets(
             sourceSets.main
        )
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    version.set("{micronaut-version}")
    processing {
        // Sets whether incremental annotation processing is enabled
        incremental.set(true)
        // Sets the module name.
        // This should be the same as the artifactId in the POM
        module.set(project.name)
        // Sets the group.
        // This should be th same as the groupId in the POM
        group.set(project.group)
        // Sets the Java package names containing any custom Micronaut
        // meta annotations (new annotations annotated with say @Around).
        // Generally used only for advanced cases such as defining new AOP
        // advice. If omitted however, incremental annotation processing
        // will not work correctly
        annotations.add("com.example.*")
        // additional sourceSets can be configured here to apply the BOM
        // and annotation processors to source sets other than 'main'
        sourceSets(
             sourceSets.findByName("main")
        )
    }
}
----

NOTE: The Micronaut Library plugin also supports Groovy and Kotlin sources.

=== Kotlin Support

For Kotlin, the Kotlin `jvm` and `kapt` plugins must be configured:

.Configuring Kotlin support
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id "org.jetbrains.kotlin.jvm" version "{kotlin-version}"
    id "org.jetbrains.kotlin.kapt" version "{kotlin-version}"
    id "io.micronaut.library" version "{gradle-project-version}"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "{kotlin-version}"
    id("org.jetbrains.kotlin.kapt") version "{kotlin-version}"
    id("io.micronaut.library") version "{gradle-project-version}"
}
----

=== Minimal Build

With the `io.micronaut.library` plugin applied a minimal build to get started writing a library for Micronaut that written in Java and is tested with JUnit 5 looks like:

.A minimal build file
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id 'io.micronaut.library' version '{gradle-project-version}'
}

version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version = "{micronaut-version}"
}

dependencies {
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("io.micronaut.library") version "{gradle-project-version}"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version.set("{micronaut-version}")
}

dependencies {
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}
----

== Micronaut Application Plugin

.Applying the Micronaut Application plugin
[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id "io.micronaut.application" version "{gradle-project-version}"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id("io.micronaut.application") version "{gradle-project-version}"
}
----

The https://plugins.gradle.org/plugin/io.micronaut.application[Micronaut application plugin] extends the Micronaut Library plugin and adds the following customizations:

* Instead of the `java-library` plugin the plugin applies the Gradle `application` plugin
* Applies the `io.micronaut.graalvm` plugin
* Correctly configures Gradle for continuous build

The following additional tasks are provided by this plugin:

* `buildLayers` - Builds application layers for use in a Docker container
* `dockerfile` - Builds a Docker File for a Micronaut application
* `dockerBuild` - Builds a Docker Image using the https://github.com/bmuschko/gradle-docker-plugin[Docker Gradle plugin]
* `dockerfileNative` - Builds a Docker File for for GraalVM Native Image
* `dockerBuildNative` - Builds a Native Docker Image using GraalVM Native Image
* `nativeCompile` - Builds a GraalVM Native Image
* `testNativeImage` (since 1.1.0) - Builds a GraalVM Native Image, starts the native server and runs tests against the server
* `dockerPush` - Pushes a Docker Image to configured container registry
* `dockerPushNative` - Pushes a Docker Image built with GraalVM Native Image to configured container registry

To run an application with continuous build use the `run` task with the `-t` parameter:

[source, bash]
----
$ ./gradlew run -t
----

=== Minimal Build

With the `io.micronaut.application` plugin applied a minimal build to get started with a Micronaut server application that is written in Java and tested with JUnit 5 looks like:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id 'io.micronaut.application' version '{gradle-project-version}'
}

version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version = "{micronaut-version}"
}

dependencies {
    implementation("io.micronaut:micronaut-http-server-netty")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    mainClass = "example.Application"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("io.micronaut.application") version "{gradle-project-version}"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version.set("{micronaut-version}")
}

dependencies {
    implementation("io.micronaut:micronaut-http-server-netty")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    mainClass.set("example.Application")
}
----

=== Kotlin Support

The most simple Kotlin build using a `build.gradle(.kts)` file looks like:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id "org.jetbrains.kotlin.jvm" version "{kotlin-version}"
    id "org.jetbrains.kotlin.kapt" version "{kotlin-version}"
    id "org.jetbrains.kotlin.plugin.allopen" version "{kotlin-version}"
    id "io.micronaut.application" version "{gradle-project-version}"
}

version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version = "{micronaut-version}"
}

dependencies {
    implementation "io.micronaut:micronaut-http-server-netty"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:{kotlin-version}"
    implementation "org.jetbrains.kotlin:kotlin-reflect:{kotlin-version}")
    runtimeOnly "ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    mainClass = "example.ApplicationKt"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "{kotlin-version}"
    id("org.jetbrains.kotlin.kapt") version "{kotlin-version}"
    id("org.jetbrains.kotlin.plugin.allopen") version "{kotlin-version}"
    id("io.micronaut.application") version "{gradle-project-version}"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version.set("{micronaut-version}")
}

dependencies {
    implementation("io.micronaut:micronaut-http-server-netty")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:{kotlin-version}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:{kotlin-version}")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

application {
    mainClass.set("example.ApplicationKt")
}
----

[[native-image]]
=== GraalVM Native Image

Since version 3.0.0, the Micronaut plugins rely on the {native-gradle-plugin}[official GraalVM plugin] to build native images.

Those plugins make use of the {gradle-toolchains}[Gradle toolchains] support, which means that the SDK which is used to build the native is decorrelated from the JVM which is used to launch Gradle itself.
Said differently, you can run Gradle with OpenJDK, while still building native images using the GraalVM SDK.

The Micronaut Gradle plugin will automatically configure the toolchains support for you, but there are a few things that you should be aware of:

- running Gradle with a GraalVM SDK doesn't necessarily imply that Gradle will use the same SDK to build native images
- Gradle will try to locate a _compatible GraalVM toolchain_ to build images. You can tweak what GraalVM version to use by following the {native-gradle-plugin}#_selecting_the_graalvm_toolchain[official documentation].

[[toolchain-behavior]]
IMPORTANT: While the toolchain selection will properly select a GraalVM SDK which matches your language version requirements, it will **not** let you pick a particular GraalVM version (say, prefer 21.3 over 21.1). If your application depends on a specific GraalVM version, you will have to disable automatic detection like explained below.

If you have several GraalVM installations available, or that you want to disable the automatic toolchain recognition, we recommend that you do the following:

- setup an environment variable named `GRAALVM_HOME` pointing to your GraalVM installation
- edit your `gradle.properties` file to add the following options:

[source, subs="verbatim"]
----
# Disable Gradle automatic download of Java SDKs
org.gradle.java.installations.auto-download=false
# Disable auto-detection of Java installations
org.gradle.java.installations.auto-detect=false
# Setup explicitly that the Java version to use
# should be the one from the JAVA_HOME environment variable
org.gradle.java.installations.fromEnv=JAVA_HOME
----

Alternatively you can pass those options from the command line:

[source, bash]
----
./gradlew -Porg.gradle.java.installations.auto-download=false \
  -Porg.gradle.java.installations.auto-detect=false \
  -Porg.gradle.java.installations.fromEnv=JAVA_HOME \
  build
----

You can build a native image by running the following task:

[source, bash]
----
$ ./gradlew nativeCompile
----

And you can run it by calling the following task:

[source, bash]
----
$ ./gradlew nativeRun
----

You can tweak the native image options by configuring the `graalvmNative` extension as explained in the {native-gradle-plugin}[plugin documentation].

For example you can add options to the main image by doing:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries {
        main {
            buildArgs.add("-H:-DeleteLocalSymbols")
            buildArgs.add("-H:+PreserveFramePointer")
        }
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries {
        named("main") {
            buildArgs.add("-H:-DeleteLocalSymbols")
            buildArgs.add("-H:+PreserveFramePointer")
        }
    }
}
----

IMPORTANT: If you update an existing Micronaut application that contains the file `src/main/resources/META-INF/native-image/xxxxx/native-image.properties`, please make sure to delete the properties `-H:Name` and `-H:Class` from the file because they are managed automatically by the plugin.

==== Build "mostly static" native images

Since GraalVM 21.0 it is possible to create "mostly static" native images that can run in a _distroless_ docker image. You only need to configure the appropriate _baseImage_ and the plugin will automatically configure GraalVM:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named('dockerfileNative') {
    baseImage('gcr.io/distroless/cc-debian10')
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<io.micronaut.gradle.docker.NativeImageDockerfile>("dockerfileNative") {
    baseImage("gcr.io/distroless/cc-debian10")
}
----

In case you want to use another base image you need to set the appropriate GraalVM flag:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named('dockerfileNative') {
    baseImage(...)
    args('-H:+StaticExecutableWithDynamicLibC')
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<io.micronaut.gradle.docker.NativeImageDockerfile>("dockerfileNative") {
    baseImage(...)
    args("-H:+StaticExecutableWithDynamicLibC")
}
----

=== Testing Native Images

NOTE: This feature is independent from the official GraalVM testing support, which actually runs a test suite _within a native image_. Micronaut native test support launches a JVM test suite _against a native image server_.

Since 1.1.x of the plugin, you can also use the `testNativeImage` task to start the Micronaut native server and run tests against it.

IMPORTANT: This feature only works in combination with `micronaut-test-core` versions 2.2.1 or above. Make sure your test classpath includes at least this version of Micronaut Test.

Using this task will replace the regular embedded server used for tests with the natively built executable:

[source, bash]
----
./gradlew testNativeImage
----

It is important to note that there are some limitations to this approach in that the native server is no longer "embedded" in the test. This has the following implications:

* It is not possible to mock components using `@MockBean` or replace beans using `@Replaces` since the native server starts in a separate process and beans injected into or defined by the test are no longer shared with the application under test since it is running in a separate process.
* The native server starts with the `test` environment active, however the classpath of the application is the runtime classpath not the test classpath. This has the implication that certain testing features (like for example Testcontainers' usage of JDBC URLs to start containers) won't work and you have to explicitly start any test containers in the test itself.

If you wish to split your native image tests from your regular tests you can {gradle-docs}/java_testing.html#sec:configuring_java_integration_tests[create an additional source set for integration tests] and the plugin will add an additional task suffixed with `*NativeImage` to run the native image tests, for example: `gradle integrationTestNativeImage`.

=== Docker Support

The Micronaut plugin includes integration with the https://bmuschko.github.io/gradle-docker-plugin[Gradle Docker plugin] allowing you to easily build applications and native images using Docker containers.

Applications are built as layered JARs using the `buildLayers` task ensuring optimized Docker images for Java applications.

To build a regular Java application into a Docker container that is ready to be deployed and exposes ports `8080` you can simply do:

[source, bash]
----
$ ./gradlew dockerBuild
----

The default uses an `{default-docker-image}` base image, however you can easily switch the base image to use by using the `baseImage` property of the `dockerfile` task:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named("dockerfile") {
  baseImage = "oracle/graalvm-ce:20.3.0-java11"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<MicronautDockerfile>("dockerfile") {
  baseImage.set("oracle/graalvm-ce:20.3.0-java11")
}
----

The above examples switches to use GraalVM CE 20.3.0 as a base image.

To build the application into a Native Image you can run:

[source,bash]
----
$ ./gradlew dockerBuildNative
----

Note that for this to work you must build the application with the same GraalVM SDK as used to build the image.

To push the container to the currently configured container registry you can use either `dockerPush` or `dockerPushNative` for the native image:

[source, bash]
----
$ ./gradlew dockerPush
----

To configure the image names to push you can use the `images` setting of the `dockerBuild` task.

For example the following configures `dockerPush` to use Oracle Container Registry:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named("dockerBuild") {
    images = ["eu-frankfurt-1.ocir.io/xyzzyz/repo/my-image:$project.version"]
}

tasks.named("dockerBuildNative") {
    images = ["eu-frankfurt-1.ocir.io/xyzzyz/repo/my-image-native:$project.version"]
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<DockerBuildImage>("dockerBuild") {
    images.add("eu-frankfurt-1.ocir.io/xyzzyz/repo/my-image:$project.version")
}

tasks.named<DockerBuildImage>("dockerBuildNative") {
    images.add("eu-frankfurt-1.ocir.io/xyzzyz/repo/my-image-native:$project.version")
}
----

Notice that you can supply two different image names to push to for the JVM version and the native version of the application.

If you wish to customize the docker builds that are used, the easiest way is to run `./gradlew dockerfile` (or `dockerfileNative` for the native version) and copy the generated `Dockerfile` from `build/docker` to your root directory and modify as required.

If you wish to customize the JVM arguments or native image arguments then it is possible to do so with the `args` method of the `dockerfile` and `dockerfileNative` tasks:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named("dockerfile") {
   args("-Xmx128m")
}
tasks.named("dockerfileNative") {
   args("-Xmx64m")
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<MicronautDockerfile>("dockerfile") {
   args("-Xmx128m")
}
tasks.named<io.micronaut.gradle.docker.NativeImageDockerfile>("dockerfileNative") {
   args("-Xmx64m")
}
----

The above configuration uses a max heap setting of `128m` for Java and `64m` for native image for the application.

To add additional docker instructions to the generated Dockerfile, such as adding a HEALTHCHECK, you can do the following. The additional instructions will be added at the end of the `Dockerfile` just before the `ENTRYPOINT`.

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named("dockerfile") {
 args("-Xmx128m")
 instruction """HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"' """
}
tasks.named("dockerfileNative") {
 args("-Xmx64m")
 instruction """HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"'"""
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.named<Dockerfile>("dockerfile") {
 args("-Xmx128m")
 instruction("""HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"' """)
}
tasks.named<io.micronaut.gradle.docker.NativeImageDockerfile>("dockerfileNative") {
 args("-Xmx64m")
 instruction("""HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"'""")
}
----

You can also add any of the other instructions/commands that the docker plugin supports, see {docker-plugin}/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy[the Dockerfile task documentation].

=== Micronaut Runtimes

A higher level concept of "runtimes" is included in the Micronaut Gradle plugin which essentially allows the plugin to decide which server runtime to include in the dependencies of the application when building the application. For example consider this minimal build:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
     id 'io.micronaut.application' version '{gradle-project-version}'
}
version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version = "{micronaut-version}"
    runtime "netty"
}

dependencies {
    runtimeOnly("ch.qos.logback:logback-classic")
}

application {
    mainClass = "example.Application"
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
     id("io.micronaut.application") version "{gradle-project-version}"
}
version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version.set("{micronaut-version}")
    runtime.set("netty")
}

dependencies {
    runtimeOnly("ch.qos.logback:logback-classic")
}

application {
    mainClass = "example.Application"
}
----

Here the only dependency declared is on the logging framework to use however `runtime` is to `netty` resulting in an application that can be built and run.

If you wish to take the same and build or run it with a different runtime you can pass the `micronaut.runtime` property for the build. For example:

[source, bash]
----
./gradlew run -Pmicronaut.runtime=google_function
----

The above example run the application as a Google Cloud Function.

The available runtimes are:

* `netty` - A Netty server runtime
* `jetty` - A Jetty server runtime
* `tomcat` - A Tomcat server runtime
* `undertow` - An Undertow server runtime
* `lambda` - Allows building the application into an AWS Lambda
* `oracle_function` - A Project.fn runtime for deploying Oracle Functions
* `google_function` - A runtime for deploying Google Functions.
* `azure_function` - A runtime for deploying Azure Functions

The advantage of allowing your dependencies to be dictated by the runtime is that you can potentially take the same application and deploy it to any of the above runtimes without changes.

==== Deploying to AWS Lambda as GraalVM native image

If you are interested in deploying your Micronaut application to AWS Lambda using GraalVM you only need to set the runtime to `lambda` and execute `./gradlew buildNativeLambda`.
This task will generate a GraalVM native image inside a Docker container and then it will create the file `build/libs/your-app.zip` file ready to be deployed to AWS Lambda using a custom runtime. See more information in {aws-docs}[Micronaut AWS documentation].

The plugin will detect the host operating system architecture (based on the `os.arch` Java system property) and will install the corresponding GraalVM  binary distribution inside the Docker image.
This means that when running packaging from an X86_64 (Intel/AMD) machine, the produced native image will be an `amd64` binary, whilst on an ARM host (such as the new Mac M1) it will be an `aarch64` binary.

To override this automatic selection, you can configure the `graalArch` property in a `dockerfileNative` configuration block in your build:

[source, groovy]
----
dockerfileNative {
    graalArch.set("amd64")
}
----

=== Packaging the application

By default the plugin doesn't create a runnable fatjar when running `./gradlew assemble`.
There are a couple of options:

==== Layered application

The plugin creates a "layered" application in `build/docker/main/layers` and from that directory you can run `java -jar myapp.jar`.
It works because that directory contains a `lib` directory with all the libraries and a `resources` directory with the configuration.
Keep in mind that copying the only `.jar` file to another directory won't work.

==== Add Shadow plugin

You can add Gradle Shadow plugin so when running `./gradlew assemble` a runnable fatjar is created in `build/libs` directory.

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id "com.github.johnrengelman.shadow" version "{shadow-version}"
    ...
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id("com.github.johnrengelman.shadow") version "{shadow-version}"
    ...
}
----

== Micronaut GraalVM Plugin

The https://plugins.gradle.org/plugin/io.micronaut.graalvm[Micronaut GraalVM plugin] is applied automatically by the
https://github.com/micronaut-projects/micronaut-gradle-plugin#micronaut-application-plugin[Micronaut application plugin] (see below)
and it provides tasks to generate a GraalVM native image and also creates the GraalVM `resource-config.json` automatically with all the resources from the application.

This plugin can be applied separately if you use the `application` plugin without the `io.micronaut.application` plugin (but we strongly recommend to switch to the `io.micronaut.application` plugin in this case).

== Micronaut AOT Plugin

WARNING: The Micronaut AOT module is in experimental stages. Use at your own risk!

The `io.micronaut.aot` plugin provides integration with https://micronaut-projects.github.io/micronaut-aot/latest/guide/[Micronaut AOT].
Micronaut AOT is a module which aims at pre-computing a number of things at _build time_ in order to provide faster startup times and smaller binaries.
At the moment, the plugin supports optimizing Micronaut applications only (Micronaut libraries or functions will be supported in a future release).

It is capable of generating a number of things:

- an <<#aot:running-jit-mode,optimized jar>>, which is a jar corresponding to the regular application jar, except that it contains some optimizations computed at build time. It may contain, for example, additional classes, or even have different resources.
- an <<#aot:running-optimized-fat-jar,optimized fat jar>>, which is the same as the previous one, except that it also embeds all transitive dependencies and is a standalone executable.
- an <<#aot:running-optimized-native-binary,optimized native binary>> which is a GraalVM image compiled with Micronaut AOT optimizations
- an <<#aot:optimized-docker-image,optimized docker image>> which is a Docker image containing the optimized application
- an <<aot:optimized-docker-image,optimized native docker image>> which is a Docker image containing the optimized application compiled as a native image

IMPORTANT: Micronaut AOT is a _deployment_ optimization: it adds to build time, in order to make the final application faster to start, or the native images smaller. Therefore, if you use the AOT tasks during development, your feedback cycle will be slower (but the application will start faster). It is a good idea, however, to check the result of the optimization locally, similarly to what you'd do for a native image.

=== Configuration

The `io.micronaut.aot` plugin is an extension to the `io.micronaut.application` plugin.

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id "io.micronaut.application" version "{gradle-project-version}"
    id "io.micronaut.aot" version "{gradle-project-version}"
    ...
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id("io.micronaut.application") version "{gradle-project-version}"
    id("io.micronaut.aot") version "{gradle-project-version}"
    ...
}
----

This will add an `aot` DSL block to the `micronaut` extension, which can be used to enable optimizations:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    ...
    aot {
        // optional, override the Micronaut AOT version
        version = "1.0.1"

        // optimizations configuration
        optimizeServiceLoading = true
        convertYamlToJava = true
        precomputeOperations = true
        cacheEnvironment = true
        netty {
            enabled = true
        }
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    ...
    aot {
        // optional, override the Micronaut AOT version
        version.set("1.0.0")

        // optimizations configuration
        optimizeServiceLoading.set(true)
        convertYamlToJava.set(true)
        precomputeOperations.set(true)
        cacheEnvironment.set(true)
        netty {
            enabled.set(true)
        }
    }
}
----

In addition, you can use the `aotPlugins` configuration to declare additional AOT modules to be used:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
dependencies {
    aotPlugins 'io.micronaut.security:micronaut-security-aot:1.0.0'
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
dependencies {
    aotPlugins("io.micronaut.security:micronaut-security-aot:1.0.0")
}
----

Because Micronaut AOT is an extensible optimization engine, not all optimizations are known beforehand by the plugin, which means that not all of them may be accessible via the DSL.
For this reason, it is possible to provide a _Micronaut AOT configuration file_ instead:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    ...
    aot {
        configFile = file("gradle/micronaut-aot.properties")
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    ...
    aot {
        configFile.set(file("gradle/micronaut-aot.properties"))
    }
}
----

NOTE: You can provide both a configuration file and `aot` DSL optimizations.
The configuration will be merged, by reading the file first, then using the DSL options.

If you want to know about all possible optimizations, you can run the `createAotSampleConfigurationFiles` which will generate a couple of sample files:

The `build/generated/aot/samples/jit/jit.properties` will contain the optimizations which are relevant to an application running in the regular Java virtual machine, for example:

----
# Checks of existence of some types at build time instead of runtime
known.missing.types.enabled = true
# A list of types that the AOT analyzer needs to check for existence (comma separated)
known.missing.types.list = javax.inject.Inject,io.micronaut.SomeType

# Replaces logback.xml with a pure Java configuration (NOT YET IMPLEMENTED!)
logback.xml.to.java.enabled = true

# Precomputes Micronaut configuration property keys from the current environment variables
precompute.environment.properties.enabled = true

# Scans reactive types at build time instead of runtime
scan.reactive.types.enabled = true

# Caches environment property values: environment properties will be deemed immutable after application startup.
cached.environment.enabled = true

# Scans for service types ahead-of-time, avoiding classpath scanning at startup
serviceloading.jit.enabled = true
# The list of service types to be scanned (comma separated)
service.types = io.micronaut.Service1,io.micronaut.Service2
# A list of implementation types which shouldn't be included in the final application (comma separated)
serviceloading.rejected.impls = com.Misc,org.Bar

# Converts YAML configuration files to Java configuration
yaml.to.java.config.enabled = true

# Precomputes property sources at build time
sealed.property.source.enabled = true
----

Another file, `build/generated/aot/samples/native/native.properties` will contain the same, but with the options which are relevant to an application compiled to a _native image_:

----
# Generates GraalVM configuration files required to load the AOT optimizations
graalvm.config.enabled = true
# The list of service types to be scanned (comma separated)
service.types = io.micronaut.Service1,io.micronaut.Service2

# Checks of existence of some types at build time instead of runtime
known.missing.types.enabled = true
# A list of types that the AOT analyzer needs to check for existence (comma separated)
known.missing.types.list = javax.inject.Inject,io.micronaut.SomeType

# Replaces logback.xml with a pure Java configuration (NOT YET IMPLEMENTED!)
logback.xml.to.java.enabled = true

# Precomputes Micronaut configuration property keys from the current environment variables
precompute.environment.properties.enabled = true

# Scans reactive types at build time instead of runtime
scan.reactive.types.enabled = true

# Caches environment property values: environment properties will be deemed immutable after application startup.
cached.environment.enabled = true

# Scans for service types ahead-of-time, avoiding classpath scanning at startup
serviceloading.native.enabled = true
# The list of service types to be scanned (comma separated)
service.types = io.micronaut.Service1,io.micronaut.Service2
# A list of implementation types which shouldn't be included in the final application (comma separated)
serviceloading.rejected.impls = com.Misc,org.Bar

# Converts YAML configuration files to Java configuration
yaml.to.java.config.enabled = true

# Precomputes property sources at build time
sealed.property.source.enabled = true
----

For native images, it is important to always have the `graalvm.config.enabled` option set to `true`, otherwise the AOT optimizations will not be loaded. The plugin takes care of setting this flag to `true` for you.

It is important to understand that Micronaut AOT works _at build time_.
Therefore, some optimizations like conversion of YAML files to Java configuration will effectively disable the ability to change the configuration at runtime.

[[aot:running-jit-mode]]
=== Running an optimized application

The plugin provides a couple of tasks aimed at running an optimized application.
The first one, `optimizedJar`, will simply run the AOT compiler and produce an "optimized" jar.
If you want to run the application with the resulting jar, you will need to call the `optimizedRun` task instead, which will create the jar and then start the application.

If you also have the `distribution` plugin applied, the optimized jar will be used to create optimized distributions, in which case you can call the `optimizedDistZip` task to create a distribution zip, the `optimizedDistTar` to create an optimized distribution tar file, or `installOptimizedDist` to install the optimized application to the `build/install` directory.

[[aot:running-optimized-fat-jar]]
=== Running an optimized fat jar

The plugin supports building an optimized fat jar. You will need to apply the `shadow` plugin to enable this feature:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id "com.github.johnrengelman.shadow" version "{shadow-version}"
    ...
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    ...
    id("com.github.johnrengelman.shadow") version "{shadow-version}"
    ...
}
----

Then you can generate the fat jar by calling: `./gradlew optimizedJitJarAll`.
The task will generate a fat jar in the `build/libs` directory, that you can run using:

`java -jar build/libs/myapp-0.1-all-optimized.jar`

[[aot:running-optimized-native-binary]]
=== Building and running an optimized native application

The plugin creates a new native binary called `optimized`.
The GraalVM plugin will then automatically create a couple of tasks for you:

- the `nativeOptimizedCompile` task will compile a native image with the AOT optimizations
- the `nativeOptimizedRun` task will run the optimized native image (you can call this task directly, it will precompile the native image before)

[[aot:optimized-docker-image]]
=== Building an optimized Docker image

It is also possible to build an optimized application and package it into a Docker image.
For this, you need to call `./gradlew optimizedDockerBuild`.
It will produce a docker image that you can start using `docker run`.

Alternatively, you can call `./gradlew optimizedDockerPush` to push the generated image to your docker registry.

All configuration options which apply to the standard docker image are also available to the optimized Docker images.

[[aot:optimized-native-docker-image]]
=== Building an optimized native Docker image

This task also produces a Docker image, but it will build a native image containing the optimized application _within a container_, in order to produce a Docker image which runs the optimized application natively.

The 2 tasks which are available for this are:

- `optimizedDockerBuildNative` to build the optimized native Docker image
- `optimizedDockerPushNative` to push the optimized native Docker image


[[test-resources]]
== Automatic test resources provisioning

The Micronaut Gradle plugin integrates with https://github.com/micronaut-projects/micronaut-test-resources[Micronaut Test Resources] to automatically provision test resources.
In particular, it makes use of https://testcontainers.org/[Testcontainers] to automatically provide resources like databases or other external services like Kafka or RabbitMQ.

Test resources are handled by a "test resources service" which is a server accepting requests for test resources, which <<sec:test-resources-lifecycle,lifecycle>> is handled by the Gradle plugin.
A test resources request is, to simplify, a request to resolve a _missing configuration property_.
For example, if the `kafka.bootstrap-servers` property isn't set, Micronaut will query the test resources service for the value of this property.
This will trigger the creaton of a a Kafka test container, and the service will answer with the URI to the bootstrap server.

[NOTE]
====
The test resources service makes use of https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html[Class Data Sharing] on Java 17+ in order to make startup faster.
In general, this shouldn't be a problem but there may be cases where the test resources service fails to load because of a https://bugs.openjdk.org/browse/JDK-8290417[bug in the JDK].
Should this happen to you, you can disable class data sharing explicitly using this configuration:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.withType(StartTestResourcesService).configureEach {
    useClassDataSharing = false
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
tasks.withType<StartTestResourcesService>().configureEach {
    useClassDataSharing.set(false)
}
----
====

=== The test resources plugin

The easiest way to add test resources support is to apply the `io.micronaut.test-resources` plugin:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id "io.micronaut.application" version "{micronaut-version}"
    id "io.micronaut.test-resources" version "{micronaut-version}"
    ...
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("io.micronaut.application") version "{micronaut-version}"
    id("io.micronaut.test-resources") version "{micronaut-version}"
    ...
}
----

Adding this plugin will be sufficient for most use cases.
This will let Gradle automatically start containers, for example, when a particular property is not present in your configuration and that you run tests (`./gradlew test`) or the application in development mode (`./gradlew run` or `./gradlew -t run`).

For example, if the `datasources.default.url` configuration property is missing, and that your configuration contains:

[source,yaml]
----
datasources:
  default:
    dialect: MYSQL
----

Then a MySQL database will automatically be started and available for use in your tests: the `url`, `username` and `password` configuration properties will automatically be injected to your application.

Please refer to the {testresources-guide}/[Micronaut Test Resources documentation] for a list of all supported modules and their configuration options.

=== Configuring the test resources plugin

In addition, the plugin will add a `testResources` extension to the `micronaut` configuration block, providing a number of options:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    testResources {
        enabled = true // true by default
        version = "1.0.0" // override Micronaut Test Resources version
        explicitPort = 15471 // by default, uses a random port
        inferClasspath = true // true by default
        additionalModules.add(JDBC_MYSQL) // empty by default
        clientTimeout = 60 // in seconds, maximum time to wait for resources to be available, 60s by default
        sharedServer = true // false by default
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
micronaut {
    testResources {
        enabled.set(true) // true by default
        version.set("1.0.0") // override Micronaut Test Resources version
        explicitPort.set(15471) // by default, uses a random port
        inferClasspath.set(true) // true by default
        additionalModules.add(JDBC_MYSQL) // empty by default
        clientTimeout.set(60) // in seconds, maximum time to wait for resources to be available, 60s by default
        sharedServer.set(true) // false by default
    }
}
----

- the `version` property will let you override the default version of Micronaut Test Resources that the plugin uses.
- the `enabled` property can let you disable test resources provisioning (for example depending on the environment).
- by default, a test resources server will be started. This server uses a randomly available port, but you can override this by setting the `explicitPort` property instead.
- by default, the plugin will automatically determine which modules to add to the test resources support, by inspecting the dependencies declared in the project. For example, if you use both `micronaut-data-jdbc` and `mysql-connector-java`, it will automatically add support for MySQL provisioning. Under some circumstances, you might want to disable this behavior by setting the `inferClasspath` property to `false`.
- the `additionalModules` property can be used to explicitly declare test resources modules to be loaded. This is useful if inference failed to detect a module, or if you want to use <<sec:standalone-test-resources,a standalone test resources service>>.
- if set to `true`, then the test server which is used by the project can be shared between independent builds (e.g different Git repositories): this can be useful in conjunction with a <<sec:standalone-test-resources,a standalone test resources service>>, where for example a producer is used in one project, and a consumer is defined in another, but both need to use the same messaging server.

[NOTE]
====
The `additionalModules` property can be used to declare {testresources-guide}[Micronaut Test Resources] modules. However, it might be necessary to add more libraries on the test resources classpath. For example, you may need to add additional JDBC drivers. For this, you can use the `testResourcesService` configuration:
[source,groovy]
----
dependencies {
    // declare an additional dependency on test resources classpath
    testResourcesService "my:jdbc-driver:1.0"
}
----
====

[[sec:standalone-test-resources]]
=== Standalone test resources service

The `io.micronaut.test-resources` plugin works particularly well in single-module projects, or in multi-projects where test resources are not shared between modules.
However, in some cases, you may want to reuse test containers for multiple projects of the same multi-project build, in order to save startup times for example.

For this purpose, the `io.micronaut.test-resources` plugin can be applied on a project independently of the application or library plugins.

For example, imagine a multi-project build which consists of :

- a Kafka consumer
- a Kafka producer
- functional tests integrating both

If each project applies the `io.micronaut.test-resources` plugin independently, then each project will use its own test server, independently of the others.

However, you might want to run the consumer in one terminal, and the producer in another, and still want them to talk to the _same_ Kafka cluster.
For this you have a couple options:

    1. you can use a shared test server, by setting the `sharedServer` property to `true` in the `testResources` extension.
    2. you can define a distinct project which role is to handle the test resources lifecycle

The first solution comes with a major drawback: _shared servers_ are shared by all projects in the multi-project build, but also between projects of the same build. However the configuration of the server will depend on the _first one started_.

To avoid this problem it is recommended to declare a distinct project to handle test resources.
Here, we're going to add a project called `shared-testresources` which is going to be a _test resources provider_:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
// shared-testresources/build.gradle
plugins {
    id "io.micronaut.test-resources" version "{micronaut-version}" // <1>
}

micronaut {
    testResources {
        additionalModules.add(KAFKA)                 // <2>
    }
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
// shared-testresources/build.gradle.kts
plugins {
    id("io.micronaut.test-resources") version "{micronaut-version}" // <1>
}

micronaut {
    testResources {
        additionalModules.add(KAFKA)                  // <2>
    }
}
----
<1> use `test-resources` as a standalone plugin
<2> declare that it will provide Kafka containers

Then each consumer of test resources need to apply the `io.micronaut.test-resources-consumer` plugin instead:

[source, groovy, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id "io.micronaut.application" version "{micronaut-version}"
    id "io.micronaut.test-resources-consumer" version "{micronaut-version}" // <1>
}

dependencies {
    testResourcesService project(':shared-testresources')           // <2>
}
----

[source, kotlin, subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
    id("io.micronaut.application") version "{micronaut-version}"
    id("io.micronaut.test-resources-consumer") version "{micronaut-version}" // <1>
}

dependencies {
    testresources(project(":shared-testresources"))           // <2>
}
----
<1> Use the test resources consumer plugin instead
<2> Declare that it consumes test resources provided by the `:testresources` project

Now Gradle will automatically start test resources when one of the project needs them, and reuse them in all consumer projects.

[[sec:test-resources-lifecycle]]
=== Test resources lifecycle

Test resources are handled by a service which is, by default, started at the beginning of a build, and stopped at the end.

For example, if you invoke:

`./gradlew test`

Then the test resources service will be started before tests are executed, then tests will share the resources provided by the service.
Any test resource started during the test will be stopped _when the build finishes_.

In https://docs.gradle.org/current/userguide/userguide.html#sec:continuous_build[continuous mode], the test resources are shared between builds.
For example, if you run:

`./gradlew -t test` (run test in continuous mode)

Then the test resources will be spawned during the first execution of tests.
If you make any change to sources (production or test) and save the files, Gradle will rebuild the project and run the tests _using the same test resources_.
This behavior can be extremely useful to save time since typically Docker containers would only be spawned once.
If you interrupt the continuous build, the test resources will be stopped.

[sec:keepalive-test-resources]
=== Keeping test resources alive

We have seen that running in continous mode allows keeping test resources alive as long as a continous build runs.
However, what if you want to start the test resources service in the background, and keep it alive for multiple, independent builds (different invocations on the command line for example) ?

You can achieve this behavior by running the `startTestResourcesService` command:

`./gradlew startTestResourcesService`

This command **must** be the only command executed: it will start a test resources service in the background, which will be shared between builds.
Therefore, it's your responsibility to stop the service when you are done by running:

`./gradlew stopTestResourcesService`

WARNING: When keeping a test resources service alive, you must understand that any change to the test resources configuration will be ignored until you stop the service.

[sec:custom-test-resources]
=== Implementing your own test resources resolver

https://github.com/micronaut-projects/micronaut-test-resources[Micronaut Test Resources] provides integration with a lot of databases and services, and also supports a {testresources-guide}/#modules-testcontainers[fully declarative way] to spawn test containers.
However, there are cases where you might need to implement your own test resources resolver.

The plugin makes it extremely straightforward: it declares an additional source set called `testResources`.
You therefore write your test resources directly in `src/testResources/java` for example, and the test resource will be automatically made available.

For example, let's write a test resource which provides the value of the `greeting.message` property.

First, let's create the `src/testResources/java/demo/GreetingTestResource.java` file:

.src/testResources/java/demo/GreetingTestResource.java
[source, java]
----
include::samples/test-resources/custom-test-resource/src/testResources/java/demo/GreetingTestResource.java[]
----

Then you need to declare the test resource in the service file descriptor:

.src/testResources/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
[source, text]
----
include::samples/test-resources/custom-test-resource/src/testResources/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver[]
----

Now the value of the `greeting.message` property will be available in your tests:

.src/test/java/demo/DemoTest.java
[source, java]
----
include::samples/test-resources/custom-test-resource/src/test/java/demo/DemoTest.java[tag=test]
----

You can learn more about custom test resource resolvers in the {testresources-guide}/#implementing-test-resources[Micronaut Test Resources] documentation.

== Upgrade notes

=== Upgrading from 2.x

When upgrading from the 2.x version of the plugins, you will need to change the configuration of the GraalVM native image builds if you use them.

Typically, instead of configuring image compilation using the _task_:

[source,groovy]
----
nativeImage {
    imageName.set("custom")
}
----

You now need to use the `graalvmNative` extension. This extension supports building multiple native images, and the main one is named `main` (there is another one for tests, called `test`, which runs unit tests natively):

[source,groovy]
----
graalvmNative {
    binaries {
        named("main") {
            imageName.set("custom")
        }
    }
}
----

Similarly, to compile the native image, you now need to run `nativeCompile` instead of `nativeImage`.

In addition, the official GraalVM plugin makes use of Gradle toolchains support, which can lead to surprising behavior if you are used to switching between local JDKs. If you are facing errors like this one:

----
> No compatible toolchains found for request filter: {languageVersion=11, vendor=matching('GraalVM'), implementation=vendor-specific} (auto-detect true, auto-download true)
----

then we recommend tweaking toolchain detection as described in <<#toolchain-behavior, this section of the documentation>>.

In any case, make sure to follow the <<#native-image,configuration instructions>>.
