/*
 * Copyright 2003-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.gradle.aot;

import io.micronaut.aot.core.Environments;
import io.micronaut.aot.std.sourcegen.*;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.*;

import java.io.*;
import java.nio.file.Files;
import java.util.List;
import java.util.Properties;

/**
 * A task which is responsible for writing a configuration
 * file for Micronaut AOT.
 */
public abstract class MicronautAOTConfigWriterTask extends DefaultTask {

    public static final String GENERATED_BY_GRADLE_COMMENT = "Generated by Gradle";

    /**
     * Avoids linking against Micronaut runtime classes from Gradle task classpath.
     * <p>
     * These values are defined by {@code io.micronaut.aot.std.sourcegen.GenericPropertySourceGenerator},
     * but accessing its non-constant static fields may trigger class initialization which requires
     * Micronaut runtime classes (for example {@code io.micronaut.core.io.ResourceLoader}).
     */
    private static final String PROPERTY_SOURCE_LOADER_TYPES_KEY = "property-source-loader.types";
    private static final String YAML_PROPERTY_SOURCE_LOADER_TYPE = "io.micronaut.context.env.yaml.YamlPropertySourceLoader";
    private static final String YAML_TO_JAVA_CONFIG_ID = "yaml.to.java.config";

    @InputFile
    @PathSensitive(PathSensitivity.NONE)
    @Optional
    public abstract RegularFileProperty getUserConfiguration();

    @Input
    public abstract Property<Boolean> getForNative();

    @Nested
    public abstract Property<AOTOptimizations> getAOTOptimizations();

    @OutputFile
    public abstract RegularFileProperty getOutputFile();

    private static void booleanOptimization(Properties props, String optimizationId, Provider<Boolean> provider) {
        if (provider.isPresent()) {
            String key = optimizationId + ".enabled";
            props.computeIfAbsent(key, (k) -> String.valueOf(provider.get()));
        }
    }

    private static void stringListParameter(Properties props, String parameter, ListProperty<String> provider) {
        if (provider.isPresent()) {
            List<String> elements = provider.get();
            if (!elements.isEmpty()) {
                props.computeIfAbsent(parameter, (k) -> String.join(",", elements));
            }
        }
    }
    private static void stringParameter(Properties props, String parameter, Property<String> provider) {
        if (provider.isPresent()) {
            props.setProperty(parameter, provider.get());
        }
    }

    @TaskAction
    void writeConfigFile() {
        var props = new Properties();
        if (getUserConfiguration().isPresent()) {
            try (var in = new FileInputStream(getUserConfiguration().getAsFile().get())) {
                props.load(in);
            } catch (IOException e) {
                throw new GradleException("Unable to parse configuration file", e);
            }
        }
        AOTOptimizations optimizations = getAOTOptimizations().get();
        if (optimizations.getConfigurationProperties().isPresent()) {
            props.putAll(optimizations.getConfigurationProperties().get());
        }
        if (!props.containsKey(KnownMissingTypesSourceGenerator.OPTION.key())) {
            props.setProperty(KnownMissingTypesSourceGenerator.OPTION.key(), String.join(",", MicronautAotPlugin.TYPES_TO_CHECK));
        }
        if (optimizations.getOptimizeServiceLoading().isPresent() && optimizations.getOptimizeServiceLoading().get()) {
            getLogger().warn("The 'optimizeServiceLoading' optimization is enabled but has been removed from Micronaut AOT. Please remove it from your configuration.");
        }
        booleanOptimization(props, GraalVMOptimizationFeatureSourceGenerator.ID, getForNative());
        booleanOptimization(props, LogbackConfigurationSourceGenerator.ID, optimizations.getReplaceLogbackXml());
        booleanOptimization(props, CachedEnvironmentSourceGenerator.ID, optimizations.getCacheEnvironment());
        booleanOptimization(props, GenericPropertySourceGenerator.ID, optimizations.getConvertYamlToJava());
        booleanOptimization(props, KnownMissingTypesSourceGenerator.ID, optimizations.getOptimizeClassLoading());
        booleanOptimization(props, PublishersSourceGenerator.ID, optimizations.getOptimizeClassLoading());
        if (optimizations.getConvertYamlToJava().isPresent() && optimizations.getConvertYamlToJava().get()) {
            String typesKey = PROPERTY_SOURCE_LOADER_TYPES_KEY;
            String yamlLoaderType = YAML_PROPERTY_SOURCE_LOADER_TYPE;
            if (!props.containsKey(typesKey)) {
                props.setProperty(typesKey, yamlLoaderType);
            } else {
                String existing = String.valueOf(props.get(typesKey));
                if (!existing.contains(yamlLoaderType)) {
                    props.setProperty(typesKey, existing + "," + yamlLoaderType);
                }
            }
            booleanOptimization(props, ConstantPropertySourcesSourceGenerator.ID, optimizations.getConvertYamlToJava());
            // keep compatibility with older AOT versions / existing tests which still look for this option
            booleanOptimization(props, YAML_TO_JAVA_CONFIG_ID, optimizations.getConvertYamlToJava());
        }
        booleanOptimization(props, EnvironmentPropertiesSourceGenerator.ID, optimizations.getPrecomputeOperations());
        booleanOptimization(props, DeduceEnvironmentSourceGenerator.ID, optimizations.getDeduceEnvironment());
        stringListParameter(props, Environments.POSSIBLE_ENVIRONMENTS_NAMES, optimizations.getPossibleEnvironments());
        stringListParameter(props, Environments.TARGET_ENVIRONMENTS_NAMES, optimizations.getTargetEnvironments());
        booleanOptimization(props, NettyPropertiesSourceGenerator.ID, optimizations.getOptimizeNetty());
        if (optimizations.getOptimizeNetty().isPresent() && optimizations.getOptimizeNetty().get()) {
            stringParameter(props, NettyPropertiesSourceGenerator.MACHINE_ID, optimizations.getNettyOptimizations().getMachineId());
            stringParameter(props, NettyPropertiesSourceGenerator.PROCESS_ID, optimizations.getNettyOptimizations().getPid());
        }
        File outputFile = getOutputFile().getAsFile().get();
        if (outputFile.getParentFile().isDirectory() || outputFile.getParentFile().mkdirs()) {
            var baos = new ByteArrayOutputStream();
            try {
                props.store(baos, GENERATED_BY_GRADLE_COMMENT);
            } catch (IOException e) {
                throw new GradleException("Unable to write output file: " + outputFile, e);
            }
            String content = baos.toString();
            try (var writer = new PrintWriter(Files.newBufferedWriter(outputFile.toPath()))) {
                content.lines()
                    .filter(line -> !line.startsWith("#") || line.contains(GENERATED_BY_GRADLE_COMMENT))
                    .forEach(writer::println);
            } catch (IOException e) {
                throw new GradleException("Unable to write output file: " + outputFile, e);
            }
        } else {
            throw new GradleException("Unable to write output file: " + outputFile);
        }
        getLogger().info("Wrote configuration file {}", outputFile);
    }
}
