{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.jsonschema",
    "module": "micronaut-json-schema-annotations",
    "version": "1.5.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT.jar",
          "url": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT.jar",
          "size": 2638,
          "sha512": "7cf4d528c8bdaf66d566a1f05469695459b0e71dbafd1bd3dc727fd759226c3b5688da9c79455234f60175e3f40657a5ff84d8754598dfe9927faf23cdde395b",
          "sha256": "e56421a4f4294618fa6316713ffb17eff09319814abb2989a0a19d8eec3eec17",
          "sha1": "1aba587fb0d12e6cd6f595f8f6131abd58825a5e",
          "md5": "e914a7cbe45b1d4399f470ca0fd661dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject",
          "version": {
            "requires": "4.8.11"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-core-bom",
          "version": {
            "requires": "4.8.11"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT.jar",
          "url": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT.jar",
          "size": 2638,
          "sha512": "7cf4d528c8bdaf66d566a1f05469695459b0e71dbafd1bd3dc727fd759226c3b5688da9c79455234f60175e3f40657a5ff84d8754598dfe9927faf23cdde395b",
          "sha256": "e56421a4f4294618fa6316713ffb17eff09319814abb2989a0a19d8eec3eec17",
          "sha1": "1aba587fb0d12e6cd6f595f8f6131abd58825a5e",
          "md5": "e914a7cbe45b1d4399f470ca0fd661dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT-sources.jar",
          "url": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT-sources.jar",
          "size": 1597,
          "sha512": "7a50caf0bef7264aa4111b35bf9932ec8dd21b2b6dd33d826e8ace2e3b55d18087d7b41475ebdc1b8c89038d15dcde79cffbf6d306c1c87714a79a69789ee15a",
          "sha256": "425d7bbd5e74a4a38563ba59b3dfbbafd419759d0154e4ce230cf81849bff77e",
          "sha1": "e381277c54ec59baf2c0e57ce41fd1ff66005604",
          "md5": "2976d11f649cad4f490e9d3bc0a9ca95"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT-javadoc.jar",
          "url": "micronaut-json-schema-annotations-1.5.4-SNAPSHOT-javadoc.jar",
          "size": 81239,
          "sha512": "e1a704a7d55b2b5f9de0dcb588b90e26bbf9a646574e3c217eb0d8e23d64817f809bda4bba3345cd08a114396e2ccb36f774720a678e495300c15a583ee102c1",
          "sha256": "793506ad3818373fc5d126fa7282ee9efbd465a41ea8c86fbd356bc66daae792",
          "sha1": "eb19c063f5d43bb632d4878bdf8387b6a016824d",
          "md5": "c52edb40177d21586fa063c775d0a039"
        }
      ]
    }
  ]
}
